task: "loco"

model:
  noise_model_type: "unet"
  alpha: 0.001
  load_weights: "/N/slate/cwseitz/cvdm/Sim/4x/Sim-2/weights/model_12000_a1f2c919-26ad-42f6-95f6-29beabae4038.h5" 
  load_mu_weights: null
  snr_expansion_n: 1
  zmd: False
  diff_inp: False

training:
  lr: 0.0001
  epochs: 50
  
eval:
  output_path: "/N/slate/cwseitz/cvdm/Sim/4x/Sim-2/eval_data/N500-7"
  generation_timesteps: 200
  checkpoint_freq: 1000
  log_freq: 10
  image_freq: 100
  val_freq: 200
  val_len: 10

data:
  dataset_path: "/N/slate/cwseitz/cvdm/Sim/4x/Sim-2/eval_data/N500-7/"
  n_samples: 20
  batch_size: 2
  im_size: 256

neptune:
  name: "CVDM"
  project: "cwseitz/test"
